#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Orbit Boot Screen
Created on Mon Jul 27 16:29:11 2026

@author: ethanbrown
"""

import pygame
import os


# ---------------------------------------
# Boot Messages
# ---------------------------------------

a = """Starting Orbit...
Initializing bootstrapper...
Reading configuration...
Loading environment...
Discovering hardware...
Verifying application integrity...
Building runtime...
Starting core services...
Initializing Orbit Kernel...
Allocating memory...
Creating process scheduler...
Initializing event loop...
Loading runtime libraries...
Calibrating orbital vectors...
Synchronizing quantum clocks...
Mounting virtual filesystem...
Registering internal APIs...
Loading plugin registry...
Discovering installed plugins...
Validating plugin signatures...
Building dependency graph...
Resolving dependencies...
Computing orbital solutions...
Aligning navigation grid...
Initializing command engine...
Initializing window manager...
Preparing graphics pipeline...
Warming shader pipeline...
Initializing rendering engine...
Creating rendering context...
Loading icon cache...
Building font atlas...
Loading interface assets...
Precomputing interface layout...
Preparing animation engine...
Initializing compositor...
Synchronizing display...
Building UI hierarchy...
Applying visual theme...
Configuring appearance...
Preparing workspace...
Restoring previous session...
Scanning user modules...
Loading workspace extensions...
Initializing package manager...
Compressing asset cache...
Initializing cache manager...
Warming application cache...
Optimizing execution graph...
Loading recent projects...
Preparing command palette...
Building autocomplete index...
Loading keyboard shortcuts...
Mapping system topology...
Balancing worker threads...
Synchronizing task scheduler...
Starting telemetry...
Synchronizing settings...
Loading startup extensions...
Establishing secure uplink...
Establishing secure runtime...
Verifying permissions...
Checking sandbox status...
Initializing filesystem monitor...
Initializing clipboard service...
Preparing drag-and-drop...
Starting notification manager...
Starting background workers...
Generating entropy...
Optimizing startup path...
Measuring performance...
Stabilizing runtime...
Initializing hyperspace...
Charging flux capacitor...
Rewriting reality...
Finding coffee...
Coffee not found.
Continuing anyway...
Pretending to know what it's doing...
Definitely not downloading more RAM...
Making everything 12% cooler...
Finalizing initialization...
Cleaning temporary resources...
Running startup diagnostics...
Diagnostics complete.
Performing final systems check...
Orbit Core online.
Loading complete.
Initializing user interface...
Ready.
Welcome to Orbit.
Session started."""

lines = a.splitlines()


# ---------------------------------------
# Boot Function
# ---------------------------------------

def start(lines):

    pygame.init()

    screen = pygame.display.set_mode((1280, 720), pygame.RESIZABLE)
    pygame.display.set_caption("ORBIT")

    clock = pygame.time.Clock()

    font = pygame.font.SysFont("couriernew", 28)

    # Load original background image
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    opening_path = os.path.join(BASE_DIR, "opening.jpeg")

    opening_original = pygame.image.load(opening_path).convert()    

    line_index = 0
    current_line = lines[0]
    timer = 0

    running = True
    
    total = 0

    while running:

        dt = clock.tick(60)
        timer += dt

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        # Current window size
        width, height = screen.get_size()

        # Resize background
        opening = pygame.transform.scale(opening_original, (width, height))

        # Change line every 500ms
        if timer >= 500:
            timer = 0

            if line_index < len(lines) - 1:
                line_index += 1
                current_line = lines[line_index]
            total += 1

        # Draw background
        screen.blit(opening, (0, 0))

        # Dark overlay
        overlay = pygame.Surface((width, height), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 130))
        screen.blit(overlay, (0, 0))

        # Draw current loading message
        text = font.render(current_line, True, (255, 255, 255))
        text_rect = text.get_rect(center=(width // 2, height - 70))
        screen.blit(text, text_rect)

        pygame.display.flip()
        
        if total > 92:
            running = False
    
    screen.fill((0, 0, 0))
    return screen